// ============================================================
//  HERBAL TREATMENT RECOMMENDER — Master Data File
// ============================================================

const SYMPTOMS_DB = {
  // ── Respiratory ──────────────────────────────────────────
  runny_nose:        { id:'runny_nose',        label:'Runny Nose',                    labelHi:'बहती नाक',              category:'respiratory', icon:'🤧', w:1   },
  nasal_congestion:  { id:'nasal_congestion',  label:'Nasal Congestion',              labelHi:'नाक बंद होना',           category:'respiratory', icon:'😤', w:1.2 },
  sneezing:          { id:'sneezing',          label:'Sneezing',                      labelHi:'छींकना',                 category:'respiratory', icon:'🤧', w:0.8 },
  dry_cough:         { id:'dry_cough',         label:'Dry Cough',                     labelHi:'सूखी खांसी',             category:'respiratory', icon:'😮‍💨', w:1.3 },
  wet_cough:         { id:'wet_cough',         label:'Wet / Productive Cough',        labelHi:'बलगम वाली खांसी',        category:'respiratory', icon:'😮‍💨', w:1.5 },
  chest_congestion:  { id:'chest_congestion',  label:'Chest Congestion',              labelHi:'छाती में जमाव',           category:'respiratory', icon:'🫁', w:2   },
  wheezing:          { id:'wheezing',          label:'Wheezing',                      labelHi:'सांस में घरघराहट',        category:'respiratory', icon:'🫁', w:2.5, danger:3 },
  sore_throat:       { id:'sore_throat',       label:'Sore Throat',                   labelHi:'गले में दर्द',            category:'respiratory', icon:'🤒', w:1.3 },
  hoarseness:        { id:'hoarseness',        label:'Hoarseness / Voice Loss',       labelHi:'आवाज़ बैठना',             category:'respiratory', icon:'🗣️', w:1   },
  shortness_breath:  { id:'shortness_breath',  label:'Shortness of Breath',           labelHi:'सांस लेने में तकलीफ',    category:'respiratory', icon:'😮‍💨', w:4,   danger:3 },
  // ── Fever ────────────────────────────────────────────────
  mild_fever:        { id:'mild_fever',        label:'Mild Fever (99–100.9°F)',        labelHi:'हल्का बुखार',            category:'fever',       icon:'🌡️', w:2   },
  moderate_fever:    { id:'moderate_fever',    label:'Moderate Fever (101–102.9°F)',   labelHi:'मध्यम बुखार',            category:'fever',       icon:'🌡️', w:3   },
  high_fever:        { id:'high_fever',        label:'High Fever (103°F +)',           labelHi:'तेज़ बुखार',              category:'fever',       icon:'🌡️', w:5,   danger:1 },
  chills:            { id:'chills',            label:'Chills / Shivering',            labelHi:'ठंड लगना',               category:'fever',       icon:'🥶', w:1.5 },
  night_sweats:      { id:'night_sweats',      label:'Night Sweats',                  labelHi:'रात को पसीना',           category:'fever',       icon:'💧', w:2   },
  body_aches:        { id:'body_aches',        label:'Body Aches',                    labelHi:'शरीर में दर्द',           category:'fever',       icon:'🤕', w:1.5 },
  // ── Head / Neurological ──────────────────────────────────
  headache:          { id:'headache',          label:'Headache',                      labelHi:'सिरदर्द',                category:'head',        icon:'🤕', w:1.5 },
  migraine:          { id:'migraine',          label:'Migraine',                      labelHi:'माइग्रेन',               category:'head',        icon:'🤕', w:3   },
  dizziness:         { id:'dizziness',         label:'Dizziness / Vertigo',           labelHi:'चक्कर आना',              category:'head',        icon:'😵', w:2   },
  brain_fog:         { id:'brain_fog',         label:'Brain Fog',                     labelHi:'दिमाग में धुंध',          category:'head',        icon:'🧠', w:1.5 },
  eye_strain:        { id:'eye_strain',        label:'Eye Strain / Tired Eyes',       labelHi:'आँखों में थकान',          category:'head',        icon:'👁️', w:1   },
  sinus_pressure:    { id:'sinus_pressure',    label:'Sinus Pressure',                labelHi:'साइनस का दबाव',          category:'head',        icon:'😤', w:2   },
  // ── Digestive ────────────────────────────────────────────
  indigestion:       { id:'indigestion',       label:'Indigestion / Upset Stomach',   labelHi:'अपच',                   category:'digestive',   icon:'🫃', w:1.5 },
  bloating:          { id:'bloating',          label:'Bloating',                      labelHi:'पेट फूलना',              category:'digestive',   icon:'🫃', w:1.3 },
  gas:               { id:'gas',              label:'Gas / Flatulence',              labelHi:'गैस',                   category:'digestive',   icon:'💨', w:1   },
  nausea:            { id:'nausea',            label:'Nausea',                        labelHi:'मतली',                  category:'digestive',   icon:'🤢', w:2   },
  vomiting:          { id:'vomiting',          label:'Vomiting',                      labelHi:'उल्टी',                  category:'digestive',   icon:'🤮', w:2.5 },
  acid_reflux:       { id:'acid_reflux',       label:'Acid Reflux / Heartburn',       labelHi:'एसिड रिफ्लक्स',          category:'digestive',   icon:'🔥', w:2   },
  acidity:           { id:'acidity',           label:'Acidity / Sour Burps',          labelHi:'एसिडिटी',               category:'digestive',   icon:'🔥', w:1.5 },
  constipation:      { id:'constipation',      label:'Constipation',                  labelHi:'कब्ज़',                  category:'digestive',   icon:'🚽', w:1.5 },
  diarrhea:          { id:'diarrhea',          label:'Diarrhea',                      labelHi:'दस्त',                  category:'digestive',   icon:'🚽', w:2   },
  stomach_cramps:    { id:'stomach_cramps',    label:'Stomach Cramps / Pain',         labelHi:'पेट में ऐंठन',            category:'digestive',   icon:'🤕', w:2   },
  loss_of_appetite:  { id:'loss_of_appetite',  label:'Loss of Appetite',              labelHi:'भूख न लगना',             category:'digestive',   icon:'🍽️', w:1.3 },
  mouth_ulcers:      { id:'mouth_ulcers',      label:'Mouth Ulcers / Canker Sores',   labelHi:'मुंह के छाले',           category:'digestive',   icon:'👄', w:1.5 },
  poor_digestion:    { id:'poor_digestion',    label:'Poor Digestion',                labelHi:'कमजोर पाचन',             category:'digestive',   icon:'🫃', w:1.5 },
  // ── Skin ─────────────────────────────────────────────────
  acne:              { id:'acne',              label:'Acne / Pimples',                labelHi:'मुहांसे',                category:'skin',        icon:'😖', w:1.5 },
  dry_skin:          { id:'dry_skin',          label:'Dry / Flaky Skin',              labelHi:'रूखी त्वचा',             category:'skin',        icon:'🧴', w:1   },
  oily_skin:         { id:'oily_skin',         label:'Oily Skin',                     labelHi:'तैलीय त्वचा',            category:'skin',        icon:'✨', w:1   },
  skin_rash:         { id:'skin_rash',         label:'Skin Rash / Hives',             labelHi:'त्वचा पर चकत्ते',         category:'skin',        icon:'🔴', w:2   },
  itching:           { id:'itching',           label:'Itching / Pruritis',            labelHi:'खुजली',                 category:'skin',        icon:'🤚', w:1.5 },
  eczema:            { id:'eczema',            label:'Eczema / Dermatitis',           labelHi:'एक्जिमा',               category:'skin',        icon:'🔴', w:2   },
  sunburn:           { id:'sunburn',           label:'Sunburn',                       labelHi:'धूप से जलन',             category:'skin',        icon:'☀️', w:2   },
  dark_circles:      { id:'dark_circles',      label:'Dark Circles',                  labelHi:'काले घेरे',              category:'skin',        icon:'👁️', w:0.8 },
  cold_sores:        { id:'cold_sores',        label:'Cold Sores / Fever Blisters',   labelHi:'होठों पर छाले',           category:'skin',        icon:'👄', w:1.5 },
  // ── Joints / Muscles ─────────────────────────────────────
  joint_pain:        { id:'joint_pain',        label:'Joint Pain / Arthritis',        labelHi:'जोड़ों में दर्द',          category:'joints',      icon:'🦴', w:2.5 },
  muscle_aches:      { id:'muscle_aches',      label:'Muscle Aches / Soreness',       labelHi:'मांसपेशियों में दर्द',     category:'joints',      icon:'💪', w:1.5 },
  back_pain:         { id:'back_pain',         label:'Back Pain',                     labelHi:'कमर दर्द',               category:'joints',      icon:'🦴', w:2   },
  neck_stiffness:    { id:'neck_stiffness',    label:'Neck Stiffness',                labelHi:'गर्दन में अकड़न',          category:'joints',      icon:'🦴', w:1.5 },
  inflammation:      { id:'inflammation',      label:'Swelling / Inflammation',       labelHi:'सूजन',                  category:'joints',      icon:'🔴', w:2   },
  knee_pain:         { id:'knee_pain',         label:'Knee Pain',                     labelHi:'घुटने में दर्द',          category:'joints',      icon:'🦵', w:2   },
  // ── Mental / Stress ──────────────────────────────────────
  stress:            { id:'stress',            label:'Stress / Tension',              labelHi:'तनाव',                  category:'mental',      icon:'😰', w:2   },
  anxiety:           { id:'anxiety',           label:'Anxiety / Worry',               labelHi:'चिंता',                 category:'mental',      icon:'😟', w:2.5 },
  insomnia:          { id:'insomnia',          label:'Insomnia / Poor Sleep',         labelHi:'नींद न आना',             category:'mental',      icon:'😴', w:2.5 },
  fatigue:           { id:'fatigue',           label:'Fatigue / Tiredness',           labelHi:'थकान',                  category:'mental',      icon:'😴', w:1.5 },
  low_energy:        { id:'low_energy',        label:'Low Energy',                    labelHi:'ऊर्जा की कमी',           category:'mental',      icon:'🔋', w:1.5 },
  mood_swings:       { id:'mood_swings',       label:'Mood Swings',                   labelHi:'मूड में बदलाव',           category:'mental',      icon:'😶‍🌫️', w:1.5 },
  mild_depression:   { id:'mild_depression',   label:'Low Mood / Mild Depression',    labelHi:'उदासी',                 category:'mental',      icon:'😞', w:2   },
  irritability:      { id:'irritability',      label:'Irritability',                  labelHi:'चिड़चिड़ापन',             category:'mental',      icon:'😤', w:1.5 },
  // ── Hair / Scalp ─────────────────────────────────────────
  hair_fall:         { id:'hair_fall',         label:'Hair Fall / Hair Loss',         labelHi:'बालों का झड़ना',          category:'hair',        icon:'💇', w:1.5 },
  dandruff:          { id:'dandruff',          label:'Dandruff',                      labelHi:'रूसी',                  category:'hair',        icon:'❄️', w:1   },
  dry_scalp:         { id:'dry_scalp',         label:'Dry Scalp',                     labelHi:'रूखी खोपड़ी',            category:'hair',        icon:'💆', w:1   },
  oily_scalp:        { id:'oily_scalp',        label:'Oily Scalp',                    labelHi:'तैलीय खोपड़ी',           category:'hair',        icon:'💆', w:1   },
  premature_graying: { id:'premature_graying', label:'Premature Graying',             labelHi:'असमय सफेद बाल',          category:'hair',        icon:'👴', w:1   },
  // ── Oral ─────────────────────────────────────────────────
  toothache:         { id:'toothache',         label:'Toothache',                     labelHi:'दांत दर्द',              category:'oral',        icon:'🦷', w:2   },
  bad_breath:        { id:'bad_breath',        label:'Bad Breath / Halitosis',        labelHi:'सांस की बदबू',           category:'oral',        icon:'💨', w:1   },
  bleeding_gums:     { id:'bleeding_gums',     label:'Bleeding Gums',                 labelHi:'मसूड़ों से खून',          category:'oral',        icon:'🩸', w:2   },
  // ── Other ────────────────────────────────────────────────
  ear_pain:          { id:'ear_pain',          label:'Ear Pain / Earache',            labelHi:'कान में दर्द',            category:'other',       icon:'👂', w:2   },
  menstrual_cramps:  { id:'menstrual_cramps',  label:'Menstrual Cramps',              labelHi:'मासिक धर्म में ऐंठन',     category:'other',       icon:'🩺', w:2   },
  pms:               { id:'pms',              label:'PMS Symptoms',                  labelHi:'पीएमएस',                category:'other',       icon:'🩺', w:1.5 },
  low_immunity:      { id:'low_immunity',      label:'Frequent Illnesses / Low Immunity', labelHi:'बार-बार बीमार पड़ना', category:'other',       icon:'🛡️', w:2   },
  urinary_burning:   { id:'urinary_burning',   label:'Urinary Burning (UTI symptoms)', labelHi:'पेशाब में जलन',         category:'other',       icon:'🚽', w:2.5 },
  eye_irritation:    { id:'eye_irritation',    label:'Eye Irritation / Redness',      labelHi:'आँखों में जलन',           category:'other',       icon:'👁️', w:1.5 },
  chest_pain:        { id:'chest_pain',        label:'Chest Pain / Pressure',         labelHi:'सीने में दर्द',           category:'other',       icon:'❤️', w:5,   danger:1 },
  excessive_thirst:  { id:'excessive_thirst',  label:'Excessive Thirst',              labelHi:'अत्यधिक प्यास',           category:'other',       icon:'💧', w:2   },
  cold_intolerance:  { id:'cold_intolerance',  label:'Cold Intolerance',              labelHi:'ठंड सहन न होना',          category:'other',       icon:'🥶', w:1.5 },
  palpitations:      { id:'palpitations',      label:'Heart Palpitations',            labelHi:'दिल की धड़कन',            category:'other',       icon:'❤️', w:3,   danger:2 },
};

// ──────────────────────────────────────────────────────────────────────────────
//  HERBS DATABASE
// ──────────────────────────────────────────────────────────────────────────────
const HERBS_DB = {
  ginger:     { id:'ginger',     name:'Ginger',               hindi:'Adrak (अदरक)',          sci:'Zingiber officinale',          cat:'Root',          emoji:'🫚', color:'#D4A017', desc:'One of the most widely used herbs globally. Known for powerful anti-inflammatory and antioxidant properties, used for thousands of years to treat nausea, digestive issues, cold, and pain.', props:['Anti-inflammatory','Antioxidant','Digestive','Antimicrobial','Warming'], benefits:['Relieves nausea','Reduces muscle pain','Helps indigestion','Boosts immunity','Lowers blood sugar'], precautions:['May interact with blood thinners','Avoid high doses in pregnancy','Can cause heartburn'], uses:['Cold','Nausea','Indigestion','Joint Pain','Headache'] },
  turmeric:   { id:'turmeric',   name:'Turmeric',             hindi:'Haldi (हल्दी)',         sci:'Curcuma longa',                cat:'Root',          emoji:'🌿', color:'#F4A300', desc:'The golden spice of India. Contains curcumin — one of nature\'s most potent anti-inflammatory compounds. Used in Ayurveda for 4,000+ years.', props:['Anti-inflammatory','Antioxidant','Antimicrobial','Analgesic','Immune-boosting'], benefits:['Powerful natural anti-inflammatory','Enhances antioxidant capacity','Improves brain function','Helps with arthritis','Natural wound healing'], precautions:['May stain skin/clothing','Interacts with blood thinners','High doses cause stomach upset'], uses:['Inflammation','Joint Pain','Skin Issues','Immunity','Digestion'] },
  tulsi:      { id:'tulsi',      name:'Tulsi (Holy Basil)',   hindi:'Tulsi (तुलसी)',         sci:'Ocimum tenuiflorum',           cat:'Herb',          emoji:'🌿', color:'#52B788', desc:'Called the "Queen of Herbs" in Ayurveda. A powerful adaptogen that helps the body manage stress, boosts immunity, and fights respiratory infections.', props:['Adaptogenic','Antimicrobial','Expectorant','Immunomodulator','Anti-stress'], benefits:['Reduces stress and anxiety','Fights respiratory infections','Powerful immune booster','Reduces fever','Supports oral health'], precautions:['May slow blood clotting','Avoid high doses in pregnancy','Can lower blood sugar'], uses:['Cold','Fever','Stress','Immunity','Respiratory'] },
  neem:       { id:'neem',       name:'Neem',                 hindi:'Neem (नीम)',            sci:'Azadirachta indica',           cat:'Tree',          emoji:'🌳', color:'#40916C', desc:'Called the "village pharmacy." Every part of the neem tree has medicinal properties. Renowned for antibacterial, antifungal, and antiviral properties used for 4,500+ years.', props:['Antibacterial','Antifungal','Antiviral','Anti-inflammatory','Blood-purifying'], benefits:['Treats acne and eczema','Natural dental care','Blood purification','Boosts immunity','Fights fungal infections'], precautions:['Not safe in pregnancy','Not for young children internally','May lower blood sugar','External use safer'], uses:['Acne','Skin Issues','Oral Health','Infections'] },
  ashwagandha:{ id:'ashwagandha',name:'Ashwagandha',          hindi:'Ashwagandha (अश्वगन्धा)',sci:'Withania somnifera',          cat:'Root',          emoji:'🌱', color:'#8B5E3C', desc:'One of the most powerful Ayurvedic herbs. Called "Indian Ginseng," it is a potent adaptogen that reduces stress, boosts brain function, and has remarkable anti-anxiety properties.', props:['Adaptogenic','Anti-stress','Anti-inflammatory','Neuroprotective','Immunomodulator'], benefits:['Reduces cortisol and stress','Reduces anxiety and depression','Improves athletic performance','Improves brain function','Fights infections'], precautions:['Not in pregnancy','May lower blood pressure','Can cause sedation','Avoid with autoimmune diseases'], uses:['Stress','Anxiety','Insomnia','Fatigue','Joint Pain'] },
  brahmi:     { id:'brahmi',     name:'Brahmi',               hindi:'Brahmi (ब्राह्मी)',     sci:'Bacopa monnieri',              cat:'Herb',          emoji:'🌾', color:'#74C69D', desc:'A staple in Ayurvedic medicine renowned for enhancing brain function, reducing anxiety, and improving memory. One of the most widely used herbs for cognitive enhancement.', props:['Nootropic','Adaptogenic','Antioxidant','Anti-anxiety','Neuroprotective'], benefits:['Improves memory and cognition','Reduces anxiety and stress','Lowers blood pressure','Anti-inflammatory','May help with ADHD'], precautions:['Can cause nausea on empty stomach','May interact with thyroid meds','Start with small doses'], uses:['Memory','Stress','Anxiety','Brain Health','Insomnia'] },
  amla:       { id:'amla',       name:'Amla (Gooseberry)',    hindi:'Amla (आँवला)',          sci:'Phyllanthus emblica',          cat:'Fruit',         emoji:'🫐', color:'#90BE6D', desc:'One of the richest natural sources of Vitamin C — 20× more than oranges. Revered in Ayurveda as a Rasayana herb promoting longevity and immunity.', props:['Antioxidant','Immune-boosting','Hair-nourishing','Anti-aging','Digestive'], benefits:['Highest Vitamin C content','Promotes hair growth','Strong antioxidant','Improves digestion','Supports eye health'], precautions:['May lower blood sugar','Excess causes diarrhea','Sour taste can aggravate acid reflux'], uses:['Hair Fall','Immunity','Digestion','Aging','Skin'] },
  aloe_vera:  { id:'aloe_vera',  name:'Aloe Vera',            hindi:'Ghritkumari (घृतकुमारी)',sci:'Aloe barbadensis',            cat:'Succulent',     emoji:'🌵', color:'#80B918', desc:'Known as the "plant of immortality" by ancient Egyptians. Healing gel used for skin care, digestion, wound healing, and more for thousands of years.', props:['Cooling','Anti-inflammatory','Wound-healing','Digestive','Moisturizing'], benefits:['Soothes sunburn','Reduces dental plaque','Treats mouth ulcers','Aids digestion','Natural wound healing'], precautions:['Oral use in moderation','May cause diarrhea','Avoid internal use in pregnancy'], uses:['Skin Issues','Sunburn','Digestion','Acid Reflux','Mouth Ulcers'] },
  peppermint: { id:'peppermint', name:'Peppermint',           hindi:'Pudina (पुदीना)',        sci:'Mentha × piperita',           cat:'Herb',          emoji:'🌿', color:'#52B788', desc:'A hybrid mint with refreshing cooling sensation from menthol. One of the most versatile herbs for digestive issues, headaches, and respiratory problems.', props:['Cooling','Analgesic','Antispasmodic','Decongestant','Antimicrobial'], benefits:['Relieves IBS symptoms','Eases headaches (topical)','Freshens breath','Clears sinuses','Boosts energy'], precautions:['Avoid in infants (menthol risks)','Not for GERD patients','Oil must be diluted'], uses:['Headache','Digestion','Nausea','Sinusitis','Fatigue'] },
  chamomile:  { id:'chamomile',  name:'Chamomile',            hindi:'Babune ka Phool (बबूने का फूल)',sci:'Matricaria chamomilla', cat:'Flower',       emoji:'🌼', color:'#FFD166', desc:'One of the most ancient herbs known to mankind. Its gentle apple-like flavor and calming properties make it one of the world\'s most popular herbal teas.', props:['Calming','Anti-inflammatory','Antispasmodic','Digestive','Sedative'], benefits:['Promotes sleep','Reduces anxiety','Anti-inflammatory for skin','Aids digestion','Relieves menstrual pain'], precautions:['Avoid if allergic to ragweed','May interact with blood thinners','Avoid high doses in pregnancy'], uses:['Insomnia','Anxiety','Digestion','Menstrual Cramps','Skin'] },
  lavender:   { id:'lavender',   name:'Lavender',             hindi:'Lavender (लैवेंडर)',    sci:'Lavandula angustifolia',       cat:'Flower',        emoji:'💜', color:'#B5838D', desc:'Famous for its distinctive fragrance and remarkable calming properties. One of the most studied herbs for anxiety and sleep disorders.', props:['Calming','Anxiolytic','Analgesic','Antimicrobial','Antifungal'], benefits:['Reduces anxiety and stress','Improves sleep quality','Relieves headaches','Skin healing','Reduces blood pressure'], precautions:['Oil must be diluted for skin','Not for oral use in children','Can cause sedation'], uses:['Anxiety','Insomnia','Headache','Stress','Skin Issues'] },
  garlic:     { id:'garlic',     name:'Garlic',               hindi:'Lehsun (लहसुन)',        sci:'Allium sativum',               cat:'Bulb',          emoji:'🧄', color:'#F8EDD5', desc:'Used as both food and medicine throughout recorded history. Its active compound allicin is one of nature\'s most potent natural antibiotics.', props:['Antibacterial','Antiviral','Antifungal','Cardioprotective','Immune-boosting'], benefits:['Natural antibiotic','Reduces blood pressure','Lowers cholesterol','Boosts immune system','Detoxifies heavy metals'], precautions:['Strong odor','Can cause heartburn','Blood-thinning — avoid before surgery'], uses:['Cold','Infections','Heart Health','Immunity','Blood Pressure'] },
  fenugreek:  { id:'fenugreek',  name:'Fenugreek',            hindi:'Methi (मेथी)',          sci:'Trigonella foenum-graecum',    cat:'Seed',          emoji:'🌱', color:'#A4C639', desc:'One of the oldest cultivated plants with a long medicinal history. Seeds and leaves used extensively in Indian cooking and medicine.', props:['Anti-diabetic','Galactagogue','Anti-inflammatory','Digestive','Hair-nourishing'], benefits:['Lowers blood sugar','Reduces cholesterol','Promotes hair growth','Reduces menstrual pain','Aids digestion'], precautions:['Not recommended in pregnancy','Can lower blood sugar significantly','May cause allergic reactions'], uses:['Diabetes','Hair Fall','Digestion','Menstrual Cramps','Fever'] },
  fennel:     { id:'fennel',     name:'Fennel',               hindi:'Saunf (सौंफ)',          sci:'Foeniculum vulgare',           cat:'Seed',          emoji:'🌿', color:'#74C69D', desc:'A beloved digestive aid in Indian households. Its sweet licorice-like flavor comes from anethole — a powerful anti-inflammatory and antispasmodic compound.', props:['Digestive','Antispasmodic','Carminative','Anti-inflammatory','Estrogenic'], benefits:['Relieves bloating and gas','Aids digestion','Freshens breath','Reduces menstrual pain','Anti-inflammatory'], precautions:['Avoid high doses in pregnancy','Can cause photosensitivity'], uses:['Bloating','Gas','Digestion','Menstrual Cramps','Bad Breath'] },
  ajwain:     { id:'ajwain',     name:'Ajwain (Carom Seeds)', hindi:'Ajwain (अजवाइन)',       sci:'Trachyspermum ammi',           cat:'Seed',          emoji:'🌱', color:'#D4A017', desc:'A staple in Indian kitchens and medicine cabinets. With thymol as its active compound, ajwain is highly effective for digestive and respiratory problems.', props:['Carminative','Expectorant','Antimicrobial','Antifungal','Analgesic'], benefits:['Instant relief from acidity','Treats digestive issues','Relieves cold and cough','Antibacterial properties','Relieves toothache'], precautions:['Avoid in large quantities in pregnancy','May cause heartburn in some','Not for infants under 6 months'], uses:['Acidity','Gas','Cough','Cold','Toothache'] },
  licorice:   { id:'licorice',   name:'Licorice Root (Mulethi)',hindi:'Mulethi (मुलेठी)',    sci:'Glycyrrhiza glabra',           cat:'Root',          emoji:'🌿', color:'#8B5E3C', desc:'One of the most widely consumed medicinal herbs globally. Its active compound glycyrrhizin is 50× sweeter than sugar. Used in traditional medicine for thousands of years.', props:['Expectorant','Anti-inflammatory','Soothing','Antiviral','Hormonal'], benefits:['Soothes sore throat and cough','Treats stomach ulcers','Anti-inflammatory','Aids respiratory conditions','Skin lightening'], precautions:['Avoid with high blood pressure','Contraindicated in pregnancy','Can cause potassium deficiency with overuse'], uses:['Sore Throat','Cough','Acid Reflux','Skin','Immunity'] },
  cinnamon:   { id:'cinnamon',   name:'Cinnamon',             hindi:'Dalchini (दालचीनी)',    sci:'Cinnamomum verum',             cat:'Bark',          emoji:'🟤', color:'#8B4513', desc:'One of the most delicious and healthiest spices. Used medicinally since ancient times in Egypt and China. Its warm flavor comes from cinnamaldehyde.', props:['Anti-diabetic','Antioxidant','Anti-inflammatory','Antimicrobial','Warming'], benefits:['Lowers blood sugar','Reduces insulin resistance','Powerful antioxidant','Anti-inflammatory','Antimicrobial'], precautions:['Cassia cinnamon contains coumarin (toxic in high doses)','May lower blood sugar too much','Avoid with liver disease'], uses:['Blood Sugar','Digestion','Cold','Infections','Weight Management'] },
  giloy:      { id:'giloy',      name:'Giloy (Guduchi)',       hindi:'Giloy (गिलोय)',         sci:'Tinospora cordifolia',         cat:'Climbing Herb', emoji:'🌿', color:'#40916C', desc:'Called "Amrita" (root of immortality) in Ayurveda. One of the best immunity-enhancing herbs — widely used as an immune booster and fever reducer.', props:['Immunomodulator','Antipyretic','Anti-inflammatory','Antioxidant','Adaptogenic'], benefits:['Remarkable immune booster','Reduces fever effectively','Powerful antioxidant','Aids digestion','Manages blood sugar'], precautions:['Avoid with autoimmune diseases','Can lower blood sugar','Avoid in pregnancy/breastfeeding'], uses:['Immunity','Fever','Digestion','Diabetes','Recovery'] },
  moringa:    { id:'moringa',    name:'Moringa (Drumstick)',   hindi:'Sahjan (सहजन)',         sci:'Moringa oleifera',             cat:'Tree',          emoji:'🌳', color:'#52B788', desc:'Called the "miracle tree" — one of the most nutrient-dense plants on Earth. Contains all essential amino acids, vitamins, and minerals.', props:['Nutritive','Anti-inflammatory','Antioxidant','Antimicrobial','Anti-diabetic'], benefits:['Exceptionally rich in nutrients','Powerful antioxidant','Anti-inflammatory','Reduces blood sugar','Supports brain health'], precautions:['Moringa root is toxic','Not for pregnant women','May interact with thyroid medications'], uses:['Nutrition','Immunity','Blood Sugar','Energy','Inflammation'] },
  valerian:   { id:'valerian',   name:'Valerian Root',        hindi:'Tagar (तगर)',           sci:'Valeriana officinalis',        cat:'Root',          emoji:'🌿', color:'#9B59B6', desc:'Used medicinally since ancient Greece and Rome. Primarily known for sleep-inducing properties. Its name comes from Latin "valere" — to be strong and healthy.', props:['Sedative','Anxiolytic','Muscle-relaxant','Antispasmodic'], benefits:['Improves sleep quality','Reduces time to fall asleep','Reduces anxiety','Relieves menstrual cramps','Reduces blood pressure'], precautions:['Do not combine with sedatives or alcohol','May cause morning grogginess','Avoid in pregnancy'], uses:['Insomnia','Anxiety','Stress','Menstrual Cramps'] },
  eucalyptus: { id:'eucalyptus', name:'Eucalyptus',           hindi:'Nilgiri (नीलगिरी)',     sci:'Eucalyptus globulus',          cat:'Tree',          emoji:'🌿', color:'#52B788', desc:'Native to Australia, eucalyptus leaves contain cineole (eucalyptol) — a powerful respiratory compound and key ingredient in many cold remedies.', props:['Decongestant','Expectorant','Antimicrobial','Anti-inflammatory','Analgesic'], benefits:['Clears respiratory congestion','Relieves cold and flu','Reduces cough','Natural antiseptic','Soothes muscle pain'], precautions:['Oil must NEVER be taken internally','Keep away from infants','Always dilute before skin use'], uses:['Cough','Cold','Congestion','Sinusitis','Joint Pain'] },
  thyme:      { id:'thyme',      name:'Thyme',                hindi:'Ajwain ke Phool (अजवाइन के फूल)',sci:'Thymus vulgaris',     cat:'Herb',          emoji:'🌿', color:'#74C69D', desc:'Used medicinally for thousands of years. Ancient Egyptians used it in embalming. Its active compound thymol is used in modern antiseptic products.', props:['Antimicrobial','Expectorant','Antispasmodic','Antifungal','Antioxidant'], benefits:['Fights respiratory infections','Natural cough remedy','Strong antimicrobial','Rich in vitamins C and A','Supports gut health'], precautions:['Avoid high doses in pregnancy','May cause allergic reactions','Oil should always be diluted'], uses:['Cough','Bronchitis','Cold','Oral Health','Immunity'] },
  calendula:  { id:'calendula',  name:'Calendula',            hindi:'Zergul (ज़रगुल)',        sci:'Calendula officinalis',        cat:'Flower',        emoji:'🌸', color:'#FF8C00', desc:'Pot marigold flowers contain powerful anti-inflammatory and healing compounds making it one of the most popular herbs for skin conditions.', props:['Anti-inflammatory','Wound-healing','Antimicrobial','Soothing','Antifungal'], benefits:['Speeds wound healing','Reduces inflammation','Treats eczema','Natural antifungal','Reduces acne'], precautions:['Avoid in pregnancy','May cause allergic reactions in daisy-allergic people'], uses:['Skin Issues','Eczema','Wound Healing','Acne','Rashes'] },
  rosemary:   { id:'rosemary',   name:'Rosemary',             hindi:'Rusmary (रोज़मेरी)',    sci:'Salvia rosmarinus',            cat:'Herb',          emoji:'🌿', color:'#52B788', desc:'Fragrant evergreen herb. Rich in antioxidants and anti-inflammatory compounds, renowned for boosting memory, hair growth, and supporting digestion.', props:['Nootropic','Antioxidant','Anti-inflammatory','Hair-stimulating','Digestive'], benefits:['Improves memory and concentration','Promotes hair growth','Reduces inflammation','Improves mood','Supports digestion'], precautions:['Avoid high doses in pregnancy','Can cause seizures in high doses','Oil must be diluted'], uses:['Hair Fall','Memory','Digestion','Stress','Headache'] },
  cloves:     { id:'cloves',     name:'Cloves',               hindi:'Laung (लौंग)',          sci:'Syzygium aromaticum',          cat:'Flower Bud',    emoji:'🌿', color:'#8B4513', desc:'Aromatic flower buds from Indonesia. Contain eugenol — a natural anesthetic and antiseptic compound. Used as a natural toothache remedy for thousands of years.', props:['Analgesic','Antiseptic','Antimicrobial','Antioxidant','Warming'], benefits:['Relieves toothache naturally','Powerful antimicrobial','Improves digestion','Regulates blood sugar','Rich in antioxidants'], precautions:['Oil can damage oral tissues if undiluted','Not safe in high doses for children','May slow blood clotting'], uses:['Toothache','Digestion','Cold','Oral Health','Bad Breath'] },
  honey:      { id:'honey',      name:'Raw Honey',            hindi:'Shahad (शहद)',          sci:'Apis mellifera (product)',     cat:'Natural',       emoji:'🍯', color:'#E9C46A', desc:'Raw honey retains all natural enzymes, antioxidants, and antimicrobial properties. Manuka honey is particularly renowned for its therapeutic benefits.', props:['Antimicrobial','Wound-healing','Soothing','Prebiotic','Antioxidant'], benefits:['Natural cough suppressant','Soothes sore throat','Wound healing and antibacterial','Rich in antioxidants','Prebiotic for gut health'], precautions:['NEVER give to children under 1 year (botulism risk)','High in natural sugars','Not for diabetics without monitoring'], uses:['Cough','Sore Throat','Skin','Immunity','Wound Healing'] },
  triphala:   { id:'triphala',   name:'Triphala',             hindi:'Triphala (त्रिफला)',    sci:'3-herb blend',                cat:'Blend',         emoji:'🌿', color:'#8B5E3C', desc:'Meaning "three fruits" in Sanskrit — one of the most ancient Ayurvedic formulations. Contains Amla, Haritaki, and Bibhitaki. Considered a powerful Rasayana.', props:['Digestive','Detoxifying','Antioxidant','Laxative','Immunomodulator'], benefits:['Promotes digestive health','Natural mild laxative','Powerful antioxidant','Supports eye health','Dental health'], precautions:['Overuse causes diarrhea','Avoid in pregnancy','Start with small doses'], uses:['Constipation','Digestion','Immunity','Detox','Eye Health'] },
  noni:       { id:'noni',       name:'Noni',                 hindi:'Noni (नोनी)',           sci:'Morinda citrifolia',           cat:'Fruit',         emoji:'🍈', color:'#90BE6D', desc:'A tropical fruit used in Polynesian folk medicine for over 2,000 years. Rich in antioxidants, vitamins, and minerals with remarkable immunity-boosting properties.', props:['Antioxidant','Immune-boosting','Anti-inflammatory','Analgesic','Antimicrobial'], benefits:['Boosts immune system','Reduces inflammation','Antioxidant rich','May help with arthritis','Supports skin health'], precautions:['High in potassium — avoid with kidney disease','May interact with blood thinners','Avoid in liver disease'], uses:['Immunity','Inflammation','Joint Pain','Skin','Energy'] },
  shatavari:  { id:'shatavari',  name:'Shatavari',            hindi:'Shatavari (शतावरी)',    sci:'Asparagus racemosus',          cat:'Root',          emoji:'🌿', color:'#74C69D', desc:'Called the "Queen of Herbs" for women in Ayurveda. A powerful adaptogen especially beneficial for female reproductive health, hormonal balance, and immunity.', props:['Adaptogenic','Hormonal','Galactagogue','Anti-inflammatory','Immunomodulator'], benefits:['Supports female reproductive health','Balances hormones','Increases breast milk','Reduces menstrual discomfort','Boosts immunity'], precautions:['Avoid with estrogen-sensitive conditions','May cause digestive issues','Avoid in pregnancy without guidance'], uses:['Menstrual Cramps','PMS','Hormonal Balance','Immunity','Stress'] },
};

// ──────────────────────────────────────────────────────────────────────────────
//  REMEDIES DATABASE
// ──────────────────────────────────────────────────────────────────────────────
const REMEDIES = [
  {
    id:'R001', name:'Ginger Honey Lemon Tea',
    tagline:'The classic cold-buster',
    description:'A time-tested remedy that soothes respiratory discomfort, reduces fever, and boosts immunity.',
    category:'respiratory',
    symptoms:['runny_nose','sore_throat','dry_cough','mild_fever','chills','body_aches','nasal_congestion'],
    herbs:['ginger','honey','lemon'],
    ingredients:[
      { item:'Fresh ginger', amount:'1 inch piece, sliced' },
      { item:'Raw honey',    amount:'1 tablespoon' },
      { item:'Lemon juice',  amount:'1 tablespoon (half lemon)' },
      { item:'Water',        amount:'1 cup (250 ml)' },
    ],
    steps:[
      'Bring water to a boil in a small saucepan.',
      'Add sliced ginger and reduce heat. Simmer for 5–7 minutes.',
      'Strain the tea into a cup.',
      'Let it cool slightly (below 40°C / 104°F) — very important before adding honey.',
      'Stir in honey and freshly squeezed lemon juice.',
      'Drink warm. Breathe in the steam while drinking for extra benefit.',
    ],
    dosage:'2–3 cups per day',
    duration:'3–5 days',
    benefits:['Relieves nasal congestion','Soothes sore throat','Reduces cough','Boosts immunity','Provides Vitamin C'],
    precautions:['Do not add honey to boiling water (destroys enzymes)','Not for children under 1 year (honey risk)','Avoid if allergic to citrus or ginger'],
    ageMin:1, ageMax:100,
    contraindications:['blood_thinners'],
    difficulty:'Easy', prepTime:'10 min', effectiveness:4.8,
    tags:['cold','immunity','throat','fever'],
  },
  {
    id:'R002', name:'Tulsi-Ginger Kadha',
    tagline:'Ayurvedic immunity powerhouse',
    description:'A traditional Ayurvedic decoction that is the first line of defense against respiratory infections and fever.',
    category:'respiratory',
    symptoms:['mild_fever','moderate_fever','runny_nose','wet_cough','dry_cough','sore_throat','body_aches','low_immunity','chills'],
    herbs:['tulsi','ginger','cinnamon','cloves','honey'],
    ingredients:[
      { item:'Fresh tulsi leaves',  amount:'8–10 leaves' },
      { item:'Fresh ginger',        amount:'1 inch, grated' },
      { item:'Cinnamon stick',      amount:'1 small piece' },
      { item:'Cloves',              amount:'2–3 whole' },
      { item:'Black pepper',        amount:'3–4 crushed' },
      { item:'Water',               amount:'2 cups' },
      { item:'Honey',               amount:'1 tsp (optional)' },
    ],
    steps:[
      'Combine water, tulsi, ginger, cinnamon, cloves, and black pepper in a pot.',
      'Bring to a boil, then simmer on low heat for 10–15 minutes.',
      'The liquid should reduce to about 1 cup.',
      'Strain into a cup through a fine sieve.',
      'Allow to cool slightly, add honey if desired.',
      'Sip slowly while warm.',
    ],
    dosage:'1 cup, twice daily (morning and evening)',
    duration:'5–7 days',
    benefits:['Strong immune booster','Reduces fever','Clears respiratory congestion','Antibacterial and antiviral','Warming in chills'],
    precautions:['Avoid in pregnancy in high doses','Spicy — may cause heartburn in sensitive individuals','Not for children under 3'],
    ageMin:3, ageMax:100,
    contraindications:['pregnancy'],
    difficulty:'Moderate', prepTime:'20 min', effectiveness:4.9,
    tags:['fever','cold','immunity','ayurveda','kadha'],
  },
  {
    id:'R003', name:'Turmeric Golden Milk',
    tagline:'Anti-inflammatory bedtime healer',
    description:'A soothing anti-inflammatory drink that reduces pain, aids recovery, and promotes restful sleep.',
    category:'anti-inflammatory',
    symptoms:['joint_pain','muscle_aches','body_aches','insomnia','mild_fever','inflammation','low_immunity','fatigue'],
    herbs:['turmeric','ginger','cinnamon','honey'],
    ingredients:[
      { item:'Milk (dairy or plant-based)', amount:'1 cup (250 ml)' },
      { item:'Turmeric powder',             amount:'½ teaspoon' },
      { item:'Ginger powder or fresh',      amount:'¼ teaspoon or small piece' },
      { item:'Cinnamon powder',             amount:'¼ teaspoon' },
      { item:'Black pepper (ground)',        amount:'A pinch — crucial for curcumin absorption' },
      { item:'Raw honey or jaggery',        amount:'1 teaspoon' },
    ],
    steps:[
      'Pour milk into a saucepan and warm over medium heat.',
      'Add turmeric, ginger, cinnamon, and black pepper.',
      'Whisk well and heat until it just begins to simmer.',
      'Remove from heat and let it cool slightly.',
      'Add honey or jaggery and stir.',
      'Pour into a mug. Drink 30 minutes before bed for best results.',
    ],
    dosage:'1 cup each night before bed',
    duration:'2–4 weeks for chronic conditions; 3–5 days for acute symptoms',
    benefits:['Powerful anti-inflammatory','Reduces joint pain','Improves sleep quality','Boosts immunity','Rich in antioxidants'],
    precautions:['Not for people on blood thinners','Avoid if lactose intolerant (use plant milk)','High doses of turmeric can cause stomach upset'],
    ageMin:2, ageMax:100,
    contraindications:['blood_thinners'],
    difficulty:'Easy', prepTime:'8 min', effectiveness:4.7,
    tags:['anti-inflammatory','sleep','joints','immunity'],
  },
  {
    id:'R004', name:'Eucalyptus Steam Inhalation',
    tagline:'Instant congestion relief',
    description:'Steam inhalation with eucalyptus oil opens clogged nasal passages and relieves chest congestion within minutes.',
    category:'respiratory',
    symptoms:['nasal_congestion','chest_congestion','sinus_pressure','wet_cough','dry_cough','hoarseness'],
    herbs:['eucalyptus','peppermint'],
    ingredients:[
      { item:'Very hot water',         amount:'2 cups in a large bowl' },
      { item:'Eucalyptus essential oil', amount:'4–5 drops' },
      { item:'Peppermint essential oil', amount:'2 drops (optional)' },
      { item:'Large towel',            amount:'1 (for draping over head)' },
    ],
    steps:[
      'Boil water and pour into a large, heat-safe bowl.',
      'Add eucalyptus and peppermint oil drops.',
      'Sit comfortably and lean over the bowl at a safe distance.',
      'Drape the towel over your head and the bowl to trap the steam.',
      'Inhale deeply through nose for 5–10 minutes.',
      'Take breaks if you feel too hot. Keep eyes closed.',
      'Blow your nose gently afterward.',
    ],
    dosage:'2–3 times daily',
    duration:'Until congestion clears (typically 3–5 days)',
    benefits:['Instantly clears nasal passages','Loosens chest congestion','Kills airborne bacteria','Soothes inflamed airways','Reduces sinus pressure'],
    precautions:['Keep a safe distance from hot water — burn risk','Not for children under 7 years without supervision','Do not use eucalyptus oil undiluted on skin','Avoid if asthmatic (can trigger attacks in some)'],
    ageMin:7, ageMax:100,
    contraindications:['asthma'],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.6,
    tags:['congestion','breathing','sinusitis','cold'],
  },
  {
    id:'R005', name:'Peppermint Oil Headache Relief',
    tagline:'Fast-acting topical pain relief',
    description:'Diluted peppermint oil applied to the temples and forehead reduces tension headaches effectively, often within 15 minutes.',
    category:'pain',
    symptoms:['headache','migraine','sinus_pressure','neck_stiffness','eye_strain'],
    herbs:['peppermint','lavender'],
    ingredients:[
      { item:'Peppermint essential oil', amount:'2–3 drops' },
      { item:'Carrier oil (coconut/almond)', amount:'1 tablespoon' },
      { item:'Lavender essential oil', amount:'1 drop (optional)' },
    ],
    steps:[
      'Mix peppermint oil with carrier oil in a small bowl or palm.',
      'Apply a small amount to your fingertips.',
      'Gently massage the temples in circular motions.',
      'Apply a thin line across the forehead and back of neck.',
      'Breathe deeply for added effect.',
      'Leave on — do not rinse.',
    ],
    dosage:'Apply every 2–3 hours as needed',
    duration:'Use as needed',
    benefits:['Reduces tension headache pain','Cooling effect relieves pressure','Improves blood circulation','Non-drowsy unlike medication','Works within 15–30 minutes'],
    precautions:['NEVER apply undiluted oil to skin','Keep away from eyes','Not suitable for children under 7','Not for migraines with sensitivity to smell'],
    ageMin:7, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'2 min', effectiveness:4.5,
    tags:['headache','migraine','pain','topical'],
  },
  {
    id:'R006', name:'Fennel & Ajwain Digestive Water',
    tagline:'Quick digestive relief',
    description:'A simple drink that rapidly relieves gas, bloating, and indigestion using two of India\'s most trusted digestive herbs.',
    category:'digestive',
    symptoms:['bloating','gas','indigestion','stomach_cramps','acidity','poor_digestion','nausea'],
    herbs:['fennel','ajwain'],
    ingredients:[
      { item:'Fennel seeds (saunf)',  amount:'1 teaspoon' },
      { item:'Ajwain (carom seeds)', amount:'½ teaspoon' },
      { item:'Water',                amount:'1 cup' },
      { item:'Rock salt (sendha namak)', amount:'A pinch' },
    ],
    steps:[
      'Dry roast fennel and ajwain seeds in a pan on low heat for 1–2 minutes until fragrant.',
      'Add water and bring to a boil.',
      'Simmer for 5 minutes.',
      'Strain into a cup.',
      'Add a pinch of rock salt.',
      'Drink warm after meals or when symptoms occur.',
    ],
    dosage:'1 cup after meals, or as needed',
    duration:'Until symptoms subside',
    benefits:['Rapidly relieves gas and bloating','Calms stomach cramps','Improves digestion','Natural antacid','Freshens breath'],
    precautions:['Avoid ajwain in pregnancy in large quantities','May cause acid reflux if taken on empty stomach in sensitive individuals'],
    ageMin:5, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'8 min', effectiveness:4.7,
    tags:['digestion','gas','bloating','acidity'],
  },
  {
    id:'R007', name:'Aloe Vera & Licorice Acid Reflux Remedy',
    tagline:'Soothing relief for heartburn',
    description:'Aloe vera gel combined with licorice creates a soothing coating that reduces acid reflux and heals the esophageal lining.',
    category:'digestive',
    symptoms:['acid_reflux','acidity','indigestion','stomach_cramps','mouth_ulcers'],
    herbs:['aloe_vera','licorice','honey'],
    ingredients:[
      { item:'Aloe vera gel (inner leaf)',   amount:'2 tablespoons, fresh' },
      { item:'Licorice root powder (mulethi)', amount:'½ teaspoon' },
      { item:'Water',                        amount:'1 cup, lukewarm' },
      { item:'Honey',                        amount:'1 teaspoon' },
    ],
    steps:[
      'Extract fresh aloe vera gel from a leaf — use only the clear inner gel.',
      'Add to lukewarm water and blend or stir well.',
      'Add licorice powder and honey.',
      'Stir until well combined.',
      'Drink 20–30 minutes before meals.',
    ],
    dosage:'Once before each main meal (up to 3 times daily)',
    duration:'2–3 weeks',
    benefits:['Reduces acid production','Soothes inflamed esophagus','Heals stomach lining','Reduces heartburn','Natural antacid'],
    precautions:['Use only inner clear aloe gel — yellow latex is a laxative','Avoid licorice with high blood pressure','Do not exceed recommended dosage'],
    ageMin:12, ageMax:100,
    contraindications:['hypertension','kidney_disease'],
    difficulty:'Moderate', prepTime:'10 min', effectiveness:4.4,
    tags:['acid reflux','heartburn','digestion','stomach'],
  },
  {
    id:'R008', name:'Triphala Overnight Remedy',
    tagline:'Gentle overnight constipation cure',
    description:'Triphala soaked in warm water overnight is the most trusted Ayurvedic remedy for chronic constipation and improving gut health.',
    category:'digestive',
    symptoms:['constipation','poor_digestion','loss_of_appetite','bloating'],
    herbs:['triphala'],
    ingredients:[
      { item:'Triphala powder', amount:'½ teaspoon' },
      { item:'Warm water',      amount:'1 cup' },
      { item:'Honey',           amount:'½ teaspoon (optional)' },
    ],
    steps:[
      'Add triphala powder to warm water.',
      'Stir well until dissolved.',
      'For best results, soak overnight and drink first thing in the morning.',
      'Alternatively, drink 30 minutes before bedtime.',
      'Start with a smaller dose and increase gradually.',
    ],
    dosage:'Once daily at night or first thing in the morning',
    duration:'2–4 weeks for lasting benefit',
    benefits:['Relieves constipation gently','Improves gut microbiome','Detoxifies digestive system','Supports eye health','Boosts immunity'],
    precautions:['Start with small doses to avoid loose stools','Avoid in pregnancy','Not recommended for children under 12 without guidance','Excessive use can cause diarrhea'],
    ageMin:12, ageMax:100,
    contraindications:['pregnancy','diarrhea'],
    difficulty:'Easy', prepTime:'2 min', effectiveness:4.6,
    tags:['constipation','digestion','detox','gut'],
  },
  {
    id:'R009', name:'Pomegranate Peel & Ginger Diarrhea Tea',
    tagline:'Natural anti-diarrheal drink',
    description:'Pomegranate peel is rich in tannins that reduce diarrhea, combined with ginger to calm the gut and reduce inflammation.',
    category:'digestive',
    symptoms:['diarrhea','stomach_cramps','nausea','vomiting'],
    herbs:['ginger'],
    ingredients:[
      { item:'Pomegranate peel (dried or fresh)', amount:'1 tablespoon, crushed' },
      { item:'Ginger',       amount:'½ inch piece' },
      { item:'Water',        amount:'2 cups' },
      { item:'Honey',        amount:'1 teaspoon' },
    ],
    steps:[
      'Combine water, pomegranate peel, and ginger in a pot.',
      'Boil and simmer for 15 minutes.',
      'Strain into a cup.',
      'Add honey and sip slowly when cooled.',
      'Stay hydrated with extra water/ORS alongside.',
    ],
    dosage:'1 cup every 4–6 hours',
    duration:'1–3 days',
    benefits:['Reduces frequency of diarrhea','Calms stomach cramping','Anti-inflammatory gut effect','Rehydration support when combined with fluids','Antimicrobial'],
    precautions:['Stay well hydrated with water or ORS','See a doctor if diarrhea contains blood or lasts more than 3 days','Not for children under 5 without guidance'],
    ageMin:5, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'20 min', effectiveness:4.3,
    tags:['diarrhea','stomach','gut','cramps'],
  },
  {
    id:'R010', name:'Salt & Turmeric Throat Gargle',
    tagline:'Fastest sore throat relief',
    description:'A simple yet remarkably effective sore throat remedy. Salt reduces swelling by osmosis while turmeric kills bacteria and reduces inflammation.',
    category:'respiratory',
    symptoms:['sore_throat','hoarseness','dry_cough','bleeding_gums','mouth_ulcers'],
    herbs:['turmeric'],
    ingredients:[
      { item:'Warm water',      amount:'1 cup' },
      { item:'Rock salt',       amount:'½ teaspoon' },
      { item:'Turmeric powder', amount:'¼ teaspoon' },
    ],
    steps:[
      'Dissolve salt and turmeric in a cup of warm (not hot) water.',
      'Stir until fully dissolved.',
      'Take a sip and gargle for 30 seconds.',
      'Spit out and repeat until the cup is finished.',
      'Do not eat or drink for 30 minutes after gargling.',
    ],
    dosage:'3–4 times daily',
    duration:'Until sore throat resolves (2–5 days)',
    benefits:['Reduces throat swelling','Kills oral bacteria','Reduces throat pain','Soothes inflamed mucous membranes','Helps with mouth ulcers'],
    precautions:['Water should be warm, not scalding','Do not swallow — gargle only','Not suitable for young children who cannot gargle'],
    ageMin:6, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'2 min', effectiveness:4.8,
    tags:['sore throat','gargle','cold','oral health'],
  },
  {
    id:'R011', name:'Neem & Turmeric Acne Face Mask',
    tagline:'Deep-cleansing acne treatment',
    description:'Neem\'s antibacterial power combined with turmeric\'s anti-inflammatory action to treat acne, reduce redness, and purify skin.',
    category:'skin',
    symptoms:['acne','oily_skin','skin_rash','itching'],
    herbs:['neem','turmeric','honey'],
    ingredients:[
      { item:'Neem leaf powder or dried leaves', amount:'1 tablespoon' },
      { item:'Turmeric powder',                   amount:'½ teaspoon' },
      { item:'Raw honey',                         amount:'1 tablespoon' },
      { item:'Rose water or plain water',         amount:'Enough to make a paste' },
    ],
    steps:[
      'Mix neem powder, turmeric, and honey in a small bowl.',
      'Add rose water little by little until it forms a smooth paste.',
      'Wash your face with gentle cleanser and pat dry.',
      'Apply the mask evenly, avoiding eye area.',
      'Leave on for 15–20 minutes until it dries.',
      'Rinse off with lukewarm water and pat dry.',
      'Apply a light moisturizer afterward.',
    ],
    dosage:'2–3 times per week',
    duration:'4–6 weeks for visible results',
    benefits:['Kills acne-causing bacteria','Reduces redness and inflammation','Unclogs pores','Natural skin purifier','Reduces excess oil'],
    precautions:['Turmeric may temporarily stain skin yellow — rinse thoroughly','Do a patch test first','Avoid getting in eyes','Not for very dry or sensitive skin daily'],
    ageMin:13, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.5,
    tags:['acne','skin','face mask','oily skin'],
  },
  {
    id:'R012', name:'Aloe Vera & Calendula Eczema Soothe',
    tagline:'Calms inflamed, itchy skin',
    description:'Aloe vera\'s cooling anti-inflammatory properties combined with calendula\'s wound-healing compounds to calm eczema and skin irritation.',
    category:'skin',
    symptoms:['eczema','itching','skin_rash','dry_skin','sunburn','inflammation'],
    herbs:['aloe_vera','calendula'],
    ingredients:[
      { item:'Fresh aloe vera gel',         amount:'3 tablespoons' },
      { item:'Calendula oil or infused oil', amount:'1 teaspoon' },
      { item:'Lavender essential oil',      amount:'2 drops (optional)' },
    ],
    steps:[
      'Scoop fresh aloe vera gel from the leaf.',
      'Blend or whisk with calendula oil until smooth.',
      'Add lavender oil drops and mix.',
      'Store in a clean container in the refrigerator.',
      'Apply to affected skin areas 2–3 times daily.',
      'Leave on — do not rinse.',
    ],
    dosage:'Apply 2–3 times daily',
    duration:'2–6 weeks or as needed',
    benefits:['Instantly soothes itching','Reduces inflammation and redness','Moisturizes dry skin','Promotes skin healing','No harsh chemicals'],
    precautions:['Do a patch test first','Avoid on open wounds or infected skin','Calendula oil may cause reactions in those allergic to daisies'],
    ageMin:2, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.4,
    tags:['eczema','skin','itching','inflammation'],
  },
  {
    id:'R013', name:'Ashwagandha Warm Milk',
    tagline:'Stress and sleep support',
    description:'Ashwagandha in warm milk is the most recommended Ayurvedic remedy for stress, anxiety, and insomnia — calming the nervous system and improving sleep quality.',
    category:'mental',
    symptoms:['stress','anxiety','insomnia','fatigue','low_energy','mood_swings','mild_depression'],
    herbs:['ashwagandha','honey'],
    ingredients:[
      { item:'Milk (warm)',             amount:'1 cup' },
      { item:'Ashwagandha powder',      amount:'½ teaspoon' },
      { item:'Cinnamon powder',         amount:'¼ teaspoon' },
      { item:'Cardamom powder',         amount:'A pinch' },
      { item:'Honey',                   amount:'1 teaspoon' },
    ],
    steps:[
      'Warm milk in a saucepan over low heat.',
      'Add ashwagandha, cinnamon, and cardamom.',
      'Whisk well until fully dissolved.',
      'Heat for 2–3 minutes without boiling.',
      'Remove from heat, cool slightly.',
      'Add honey and stir.',
      'Drink 1 hour before bedtime.',
    ],
    dosage:'1 cup nightly',
    duration:'4–8 weeks for full adaptogenic benefit',
    benefits:['Reduces cortisol (stress hormone)','Calms anxiety naturally','Improves sleep quality','Boosts energy and mood','Enhances endurance'],
    precautions:['Not in pregnancy','May interact with thyroid or sedative medications','Start with smaller dose to assess tolerance','Not for children under 16'],
    ageMin:16, ageMax:100,
    contraindications:['pregnancy','autoimmune_disorders'],
    difficulty:'Easy', prepTime:'8 min', effectiveness:4.7,
    tags:['stress','anxiety','sleep','adaptogen'],
  },
  {
    id:'R014', name:'Chamomile & Valerian Sleep Tea',
    tagline:'Gentle natural sleep inducer',
    description:'A calming herbal tea blend that relaxes the nervous system and promotes deep, restful sleep without dependency.',
    category:'mental',
    symptoms:['insomnia','anxiety','stress','irritability','mood_swings'],
    herbs:['chamomile','valerian','lavender','honey'],
    ingredients:[
      { item:'Dried chamomile flowers or tea bag', amount:'1 tablespoon or 1 tea bag' },
      { item:'Valerian root powder or tea',        amount:'½ teaspoon' },
      { item:'Dried lavender buds',                amount:'½ teaspoon (optional)' },
      { item:'Hot water',                          amount:'1 cup' },
      { item:'Honey',                              amount:'1 teaspoon' },
    ],
    steps:[
      'Boil water and let it cool for 1 minute (it should not be fully boiling).',
      'Add chamomile, valerian, and lavender to a cup or infuser.',
      'Pour hot water over the herbs.',
      'Steep for 8–10 minutes, covered.',
      'Strain, add honey, and sip slowly.',
      'Drink 30–60 minutes before bedtime.',
    ],
    dosage:'1 cup nightly',
    duration:'Use regularly for 2–4 weeks',
    benefits:['Promotes natural sleep without dependency','Reduces anxiety','Relaxes muscle tension','Calms racing thoughts','No morning grogginess'],
    precautions:['Do not combine with prescription sedatives or alcohol','Valerian may cause vivid dreams initially','Not for children under 12','Avoid during pregnancy'],
    ageMin:12, ageMax:100,
    contraindications:['pregnancy'],
    difficulty:'Easy', prepTime:'12 min', effectiveness:4.6,
    tags:['insomnia','sleep','anxiety','stress'],
  },
  {
    id:'R015', name:'Amla & Bhringraj Hair Oil Treatment',
    tagline:'Stimulates hair growth and prevents fall',
    description:'Amla and bhringraj are the two most revered Ayurvedic herbs for hair health — this oil treatment nourishes scalp, strengthens roots, and promotes new growth.',
    category:'hair',
    symptoms:['hair_fall','premature_graying','dry_scalp','dandruff'],
    herbs:['amla','rosemary'],
    ingredients:[
      { item:'Amla powder or dried amla',    amount:'2 tablespoons' },
      { item:'Coconut oil',                  amount:'4 tablespoons (base oil)' },
      { item:'Rosemary essential oil',       amount:'5 drops' },
      { item:'Castor oil',                   amount:'1 tablespoon (for thickness)' },
    ],
    steps:[
      'Heat coconut oil on low flame.',
      'Add amla powder and stir.',
      'Simmer on very low heat for 10 minutes, stirring occasionally.',
      'Remove from heat and let it cool.',
      'Add castor oil and rosemary essential oil.',
      'Strain if needed and store in a glass bottle.',
      'Warm slightly before use. Massage into scalp for 10–15 minutes.',
      'Leave overnight or for at least 2 hours. Wash with mild shampoo.',
    ],
    dosage:'2–3 times per week',
    duration:'3 months for visible results',
    benefits:['Strengthens hair roots','Prevents hair fall','Promotes new hair growth','Prevents premature graying','Deeply nourishes scalp'],
    precautions:['Patch test for rosemary oil allergy','Do not apply to irritated or broken scalp','Castor oil may be difficult to wash out — use mild shampoo'],
    ageMin:12, ageMax:100,
    contraindications:[],
    difficulty:'Moderate', prepTime:'20 min', effectiveness:4.5,
    tags:['hair fall','hair growth','scalp','amla'],
  },
  {
    id:'R016', name:'Neem & Apple Cider Vinegar Dandruff Rinse',
    tagline:'Eliminates dandruff and scalp itch',
    description:'Neem\'s antifungal properties combined with the acidic pH balancing of apple cider vinegar eliminate the fungus causing dandruff.',
    category:'hair',
    symptoms:['dandruff','itching','oily_scalp','dry_scalp'],
    herbs:['neem'],
    ingredients:[
      { item:'Fresh neem leaves or neem oil', amount:'A handful or 5 drops of oil' },
      { item:'Apple cider vinegar',            amount:'2 tablespoons' },
      { item:'Water',                          amount:'2 cups' },
    ],
    steps:[
      'Option A (leaves): Boil neem leaves in 2 cups water for 15 minutes. Cool and strain.',
      'Option B (oil): Mix 5 drops neem oil in 2 cups warm water.',
      'Add apple cider vinegar to the neem water.',
      'After washing hair with shampoo, pour the rinse over scalp.',
      'Gently massage into scalp for 2–3 minutes.',
      'Leave for 5 minutes, then rinse with cool water.',
    ],
    dosage:'2 times per week',
    duration:'4–6 weeks',
    benefits:['Kills dandruff-causing fungus','Reduces scalp itching','Balances scalp pH','Reduces oiliness','Natural and chemical-free'],
    precautions:['Neem oil has a strong smell — rinse thoroughly','Apple cider vinegar may sting on broken skin','Do not use undiluted neem oil'],
    ageMin:10, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'20 min', effectiveness:4.4,
    tags:['dandruff','scalp','hair','antifungal'],
  },
  {
    id:'R017', name:'Clove Oil Toothache Relief',
    tagline:'Immediate toothache numbing',
    description:'Clove oil containing eugenol is a powerful natural anesthetic that has been used by dentists for centuries to relieve toothache pain.',
    category:'oral',
    symptoms:['toothache','bad_breath'],
    herbs:['cloves'],
    ingredients:[
      { item:'Clove essential oil', amount:'2–3 drops' },
      { item:'Carrier oil (coconut or olive)', amount:'1 teaspoon — for dilution' },
      { item:'Alternatively: whole clove',   amount:'1–2 whole cloves' },
    ],
    steps:[
      'Method 1 (Oil): Dilute clove oil in carrier oil. Dip a cotton ball and apply directly to the painful tooth and gum.',
      'Method 2 (Whole clove): Place a whole clove between the cheek and painful tooth. Bite down gently to release the oil.',
      'Hold in place for 10–15 minutes.',
      'Spit out. Do not swallow.',
      'Repeat as needed for pain.',
    ],
    dosage:'Apply every 3–4 hours as needed',
    duration:'Temporary relief — see a dentist for underlying cause',
    benefits:['Immediate pain numbing effect','Antibacterial','Reduces gum inflammation','All-natural dental remedy','Freshens breath'],
    precautions:['NEVER use undiluted clove oil — can cause chemical burns','Do not swallow','Seek dental treatment for the underlying cause','Not for children under 6'],
    ageMin:6, ageMax:100,
    contraindications:['blood_thinners'],
    difficulty:'Easy', prepTime:'3 min', effectiveness:4.6,
    tags:['toothache','oral','dental','pain'],
  },
  {
    id:'R018', name:'Turmeric & Coconut Oil Anti-Inflammatory Paste',
    tagline:'Targeted joint pain relief',
    description:'A potent topical paste that penetrates deep into joints to reduce inflammation, stiffness, and pain in arthritis and sports injuries.',
    category:'joints',
    symptoms:['joint_pain','muscle_aches','back_pain','knee_pain','inflammation','neck_stiffness'],
    herbs:['turmeric','ginger'],
    ingredients:[
      { item:'Turmeric powder',   amount:'1 tablespoon' },
      { item:'Ginger powder',     amount:'½ tablespoon' },
      { item:'Coconut oil',       amount:'2 tablespoons (melted)' },
      { item:'Black pepper',      amount:'A pinch (activates turmeric)' },
    ],
    steps:[
      'Mix all dry ingredients together.',
      'Add melted coconut oil and stir into a smooth paste.',
      'Apply generously to the painful joint or muscle.',
      'Gently massage in circular motions for 5–10 minutes.',
      'Cover with a warm cloth for 20–30 minutes.',
      'Rinse off with warm water.',
      'Alternatively, wrap the area with a warm bandage after application.',
    ],
    dosage:'1–2 times daily',
    duration:'Until pain reduces — typically 1–2 weeks for acute pain',
    benefits:['Reduces joint inflammation','Relieves stiffness','Improves blood flow to area','All-natural with no side effects when topical','Warming effect eases muscle spasms'],
    precautions:['Turmeric stains — wear old clothes','Do a skin patch test','Avoid on broken or sensitive skin','Do not use on deep tissue injuries without doctor clearance'],
    ageMin:8, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.3,
    tags:['joint pain','arthritis','inflammation','topical'],
  },
  {
    id:'R019', name:'Brahmi & Ashwagandha Memory Tonic',
    tagline:'Brain-boosting daily tonic',
    description:'Combines two of Ayurveda\'s most powerful nootropic herbs to enhance memory, reduce brain fog, and improve mental clarity.',
    category:'mental',
    symptoms:['brain_fog','fatigue','stress','low_energy','mild_depression','anxiety'],
    herbs:['brahmi','ashwagandha','honey'],
    ingredients:[
      { item:'Brahmi powder',       amount:'¼ teaspoon' },
      { item:'Ashwagandha powder',  amount:'¼ teaspoon' },
      { item:'Warm milk or water',  amount:'1 cup' },
      { item:'Honey',               amount:'1 teaspoon' },
      { item:'Cardamom',            amount:'A pinch' },
    ],
    steps:[
      'Warm milk or water (do not boil).',
      'Add brahmi and ashwagandha powder.',
      'Stir vigorously until dissolved.',
      'Add cardamom and cool slightly.',
      'Add honey.',
      'Drink in the morning on an empty stomach or with breakfast.',
    ],
    dosage:'Once daily in the morning',
    duration:'6–8 weeks for cognitive benefits',
    benefits:['Improves memory and recall','Reduces mental fatigue','Enhances concentration','Reduces stress hormones','Supports nervous system health'],
    precautions:['Not for children under 16','Not in pregnancy','May cause drowsiness if dose is too high','Start with lower doses'],
    ageMin:16, ageMax:100,
    contraindications:['pregnancy','thyroid_disorders'],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.4,
    tags:['memory','brain','stress','focus','nootropic'],
  },
  {
    id:'R020', name:'Giloy & Tulsi Immunity Decoction',
    tagline:'Daily immunity booster',
    description:'The ultimate Ayurvedic immunity formula combining Giloy (Amrita) and Tulsi — proven to build long-term immune resilience.',
    category:'immunity',
    symptoms:['low_immunity','fatigue','mild_fever','body_aches','low_energy'],
    herbs:['giloy','tulsi','ginger','honey'],
    ingredients:[
      { item:'Giloy stem or powder', amount:'1 inch stem chopped, or ½ tsp powder' },
      { item:'Fresh tulsi leaves',   amount:'5–6 leaves' },
      { item:'Ginger',               amount:'½ inch' },
      { item:'Black pepper',         amount:'2 crushed' },
      { item:'Water',                amount:'1.5 cups' },
      { item:'Honey',                amount:'1 tsp' },
    ],
    steps:[
      'Add giloy, tulsi, ginger, and black pepper to water.',
      'Bring to boil then simmer for 15 minutes.',
      'Strain into a cup.',
      'Cool slightly and add honey.',
      'Drink warm every morning on an empty stomach.',
    ],
    dosage:'Once daily, morning on empty stomach',
    duration:'30–90 days for immune building',
    benefits:['Dramatically boosts immune system','Reduces recurrent infections','Powerful antioxidant','Anti-fever properties','Detoxifies blood'],
    precautions:['Avoid with autoimmune conditions (may over-stimulate immune system)','Not in pregnancy','Can lower blood sugar — monitor if diabetic'],
    ageMin:5, ageMax:100,
    contraindications:['autoimmune_disorders','pregnancy'],
    difficulty:'Moderate', prepTime:'20 min', effectiveness:4.8,
    tags:['immunity','giloy','tulsi','detox'],
  },
  {
    id:'R021', name:'Moringa Amla Energy Drink',
    tagline:'Natural energy and nutrition boost',
    description:'A nutrient-dense morning drink combining two of nature\'s most powerful superfoods to combat fatigue, boost energy, and provide complete nutrition.',
    category:'energy',
    symptoms:['fatigue','low_energy','loss_of_appetite','brain_fog','low_immunity'],
    herbs:['moringa','amla'],
    ingredients:[
      { item:'Moringa leaf powder', amount:'1 teaspoon' },
      { item:'Amla powder or juice', amount:'1 teaspoon or 30ml' },
      { item:'Warm water or coconut water', amount:'1 cup' },
      { item:'Honey',               amount:'1 teaspoon' },
      { item:'Lemon juice',         amount:'½ teaspoon (optional)' },
    ],
    steps:[
      'Add moringa and amla powder to a glass.',
      'Pour warm (not hot) water or coconut water.',
      'Add honey and lemon juice.',
      'Stir well until dissolved.',
      'Drink first thing in the morning.',
    ],
    dosage:'Once daily in the morning',
    duration:'Ongoing — this is a daily wellness drink',
    benefits:['Combats fatigue and tiredness','Provides all essential amino acids','Rich in Vitamin C and iron','Boosts immune system','Improves skin and hair'],
    precautions:['Moringa root is toxic — use only leaf powder','Not for pregnant women (uterine contractions)','May interact with thyroid medications','Start with ½ tsp moringa'],
    ageMin:12, ageMax:100,
    contraindications:['pregnancy','thyroid_disorders'],
    difficulty:'Easy', prepTime:'3 min', effectiveness:4.5,
    tags:['energy','immunity','nutrition','morning'],
  },
  {
    id:'R022', name:'Castor Oil & Aloe Sunburn Remedy',
    tagline:'Cools and heals sunburned skin',
    description:'Aloe vera\'s cooling anti-inflammatory action with aloe vera provide immediate relief from sunburn and speed up skin healing.',
    category:'skin',
    symptoms:['sunburn','itching','skin_rash','inflammation'],
    herbs:['aloe_vera','calendula'],
    ingredients:[
      { item:'Fresh aloe vera gel',  amount:'4 tablespoons' },
      { item:'Calendula oil',        amount:'1 teaspoon' },
      { item:'Lavender essential oil', amount:'3 drops' },
      { item:'Refrigerate the mix',  amount:'Before use' },
    ],
    steps:[
      'Extract aloe vera gel from a fresh leaf.',
      'Mix with calendula oil and lavender essential oil.',
      'Refrigerate for 30 minutes for extra cooling effect.',
      'Apply generously to sunburned areas.',
      'Do not rub — gently pat on.',
      'Repeat every few hours.',
    ],
    dosage:'Apply every 3–4 hours',
    duration:'Until sunburn heals (3–7 days)',
    benefits:['Immediate cooling relief','Reduces inflammation and redness','Speeds skin healing','Prevents peeling','Natural and gentle'],
    precautions:['Avoid sun exposure on affected area','Stay hydrated','Do not apply to blistered or broken skin'],
    ageMin:2, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.7,
    tags:['sunburn','skin','cooling','aloe'],
  },
  {
    id:'R023', name:'Fenugreek & Cinnamon Blood Sugar Tea',
    tagline:'Natural blood sugar management',
    description:'Fenugreek seeds and cinnamon work together to improve insulin sensitivity and reduce blood sugar spikes naturally.',
    category:'metabolic',
    symptoms:['excessive_thirst','fatigue','low_energy','poor_digestion'],
    herbs:['fenugreek','cinnamon'],
    ingredients:[
      { item:'Fenugreek seeds (methi)', amount:'1 teaspoon, soaked overnight' },
      { item:'Cinnamon stick or powder', amount:'1 stick or ½ tsp' },
      { item:'Water',                    amount:'1 cup' },
      { item:'Lemon juice',              amount:'A squeeze (optional)' },
    ],
    steps:[
      'Soak fenugreek seeds in water overnight.',
      'In the morning, strain the soaked seeds and drink the water.',
      'Alternatively, boil the soaked seeds with cinnamon for 10 minutes.',
      'Strain and drink warm.',
      'Eat the soaked seeds on an empty stomach.',
    ],
    dosage:'Once daily in the morning',
    duration:'3 months with regular monitoring',
    benefits:['Improves insulin sensitivity','Reduces post-meal blood sugar spikes','Rich in soluble fiber','Anti-inflammatory','Improves digestion'],
    precautions:['Monitor blood sugar closely if diabetic','May interact with diabetes medications','Not a replacement for prescribed medication','Consult doctor if taking insulin'],
    ageMin:18, ageMax:100,
    contraindications:['pregnancy'],
    difficulty:'Easy', prepTime:'5 min (+ overnight soak)', effectiveness:4.2,
    tags:['blood sugar','diabetes','metabolic','fenugreek'],
  },
  {
    id:'R024', name:'Fennel & Shatavari Menstrual Relief Tea',
    tagline:'Eases period cramps naturally',
    description:'A soothing herbal tea that reduces menstrual cramps, eases PMS, and balances hormones using two herbs specifically effective for women\'s health.',
    category:'womens',
    symptoms:['menstrual_cramps','pms','mood_swings','bloating','back_pain'],
    herbs:['fennel','shatavari','chamomile','honey'],
    ingredients:[
      { item:'Fennel seeds',       amount:'1 teaspoon' },
      { item:'Shatavari powder',   amount:'½ teaspoon' },
      { item:'Chamomile flowers',  amount:'1 teaspoon' },
      { item:'Water',              amount:'1 cup' },
      { item:'Honey',              amount:'1 teaspoon' },
    ],
    steps:[
      'Bring water to a boil.',
      'Add fennel seeds and let simmer 3 minutes.',
      'Remove from heat, add chamomile and shatavari.',
      'Steep covered for 8 minutes.',
      'Strain into a cup.',
      'Add honey and sip slowly.',
      'Best drunk warm when cramps begin.',
    ],
    dosage:'2–3 cups daily during menstruation',
    duration:'During menstrual cycle (start 2 days before expected period for prevention)',
    benefits:['Reduces menstrual cramp intensity','Eases PMS symptoms','Balances hormones','Anti-spasmodic for uterine muscles','Mood-stabilizing'],
    precautions:['Not during pregnancy','Shatavari has hormonal effects — consult doctor with hormone-sensitive conditions','Fennel in large amounts can have estrogen-like effects'],
    ageMin:13, ageMax:60,
    contraindications:['pregnancy','hormone_sensitive_conditions'],
    difficulty:'Easy', prepTime:'12 min', effectiveness:4.5,
    tags:['menstrual','PMS','women','cramps','hormones'],
  },
  {
    id:'R025', name:'Cranberry & Coriander UTI Remedy',
    tagline:'Fights urinary tract infections',
    description:'Cranberry\'s PACs prevent bacteria from adhering to urinary walls while coriander seeds soothe urinary burning and inflammation.',
    category:'urinary',
    symptoms:['urinary_burning','stomach_cramps'],
    herbs:['fennel'],
    ingredients:[
      { item:'Pure cranberry juice (unsweetened)', amount:'200 ml' },
      { item:'Coriander seeds',                    amount:'1 tablespoon' },
      { item:'Water',                              amount:'1 cup' },
      { item:'Lemon juice',                        amount:'1 teaspoon' },
    ],
    steps:[
      'Boil coriander seeds in water for 10 minutes.',
      'Strain and cool to room temperature.',
      'Mix with cranberry juice.',
      'Add lemon juice.',
      'Drink throughout the day. Stay very well hydrated.',
    ],
    dosage:'Drink this mixture plus 2–3 liters of water daily',
    duration:'3–5 days; see a doctor if no improvement',
    benefits:['Prevents bacteria from adhering to urinary walls','Soothes urinary burning','Anti-inflammatory for urinary tract','Increases urine flow','Rich in antioxidants'],
    precautions:['This is supportive care — see a doctor if symptoms worsen or persist beyond 3 days','High-grade UTIs require antibiotics','Do not delay treatment if fever develops'],
    ageMin:12, ageMax:100,
    contraindications:['kidney_stones'],
    difficulty:'Easy', prepTime:'15 min', effectiveness:4.1,
    tags:['UTI','urinary','bladder','infection'],
  },
  {
    id:'R026', name:'Honey & Licorice Cough Syrup',
    tagline:'Soothing natural cough suppressant',
    description:'A powerful natural cough syrup that coats and soothes the throat, reduces cough reflex, and speeds healing of respiratory infections.',
    category:'respiratory',
    symptoms:['dry_cough','wet_cough','sore_throat','hoarseness','chest_congestion'],
    herbs:['honey','licorice','ginger','thyme'],
    ingredients:[
      { item:'Raw honey',            amount:'4 tablespoons' },
      { item:'Licorice root (mulethi) powder', amount:'1 teaspoon' },
      { item:'Fresh ginger juice',   amount:'1 tablespoon' },
      { item:'Thyme dried leaves',   amount:'1 teaspoon' },
      { item:'Hot water',            amount:'¼ cup' },
    ],
    steps:[
      'Steep licorice and thyme in hot water for 15 minutes.',
      'Strain and cool slightly.',
      'Add honey and ginger juice.',
      'Stir well until honey dissolves.',
      'Store in a small jar. Refrigerate.',
      'Take by the teaspoon directly or dissolved in warm water.',
    ],
    dosage:'1 teaspoon every 3–4 hours',
    duration:'5–7 days',
    benefits:['Suppresses cough naturally','Soothes throat irritation','Antibacterial and antiviral','Expectorant action loosens mucus','Boosts immunity'],
    precautions:['Not for children under 1 year (honey)','Licorice root not for people with hypertension','Store refrigerated and use within 2 weeks'],
    ageMin:1, ageMax:100,
    contraindications:['hypertension'],
    difficulty:'Moderate', prepTime:'20 min', effectiveness:4.6,
    tags:['cough','throat','cold','syrup'],
  },
  {
    id:'R027', name:'Rose Water & Cucumber Dark Circle Remedy',
    tagline:'Reduces dark circles and puffiness',
    description:'Rose water\'s anti-inflammatory and astringent properties combined with cucumber\'s cooling effect reduce dark circles, puffiness, and eye fatigue.',
    category:'skin',
    symptoms:['dark_circles','eye_strain','fatigue'],
    herbs:['aloe_vera'],
    ingredients:[
      { item:'Rose water',          amount:'2 tablespoons' },
      { item:'Cucumber slices',     amount:'2 thick slices' },
      { item:'Cold water or ice',   amount:'For chilling cucumber' },
    ],
    steps:[
      'Chill cucumber slices in the refrigerator for 15 minutes.',
      'Soak two cotton pads in rose water.',
      'Lie down and place chilled cucumber slices over eyes.',
      'Place rose water-soaked pads over cucumber slices.',
      'Relax for 15–20 minutes.',
      'Rinse gently. Apply a light eye cream if desired.',
    ],
    dosage:'Once daily, preferably at night',
    duration:'2–4 weeks for visible results',
    benefits:['Reduces dark circles','Decreases puffiness','Soothes tired eyes','Brightens under-eye area','Hydrating and refreshing'],
    precautions:['Use pure rose water without alcohol','Ensure cucumbers are clean and fresh','Avoid rose water if allergic to roses'],
    ageMin:12, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'20 min', effectiveness:4.2,
    tags:['dark circles','eyes','skin','puffy eyes'],
  },
  {
    id:'R028', name:'Ginger & Garlic Cold-Busting Soup',
    tagline:'Healing soup for cold and flu',
    description:'A warming, nutrient-rich soup that harnesses the antiviral and immune-boosting power of garlic and ginger to accelerate recovery from cold and flu.',
    category:'respiratory',
    symptoms:['runny_nose','mild_fever','body_aches','loss_of_appetite','chills','fatigue','nasal_congestion'],
    herbs:['garlic','ginger','turmeric'],
    ingredients:[
      { item:'Garlic cloves',          amount:'6–8, minced' },
      { item:'Fresh ginger',           amount:'1 inch, grated' },
      { item:'Onion',                  amount:'1 medium, chopped' },
      { item:'Turmeric',               amount:'½ teaspoon' },
      { item:'Vegetable broth',        amount:'3 cups' },
      { item:'Salt and pepper',        amount:'To taste' },
      { item:'Lemon juice',            amount:'1 tablespoon' },
    ],
    steps:[
      'Sauté onion in a pot until translucent.',
      'Add garlic and ginger, cook for 2 minutes.',
      'Add turmeric and stir.',
      'Pour in broth and bring to a boil.',
      'Simmer for 15–20 minutes.',
      'Remove from heat, add lemon juice.',
      'Serve hot. Breathe in the steam as you eat.',
    ],
    dosage:'1–2 bowls per day',
    duration:'3–5 days',
    benefits:['Provides warmth and comfort','Antiviral compounds fight infection','Boosts immune system','Easy to digest when ill','Hydrating and nourishing'],
    precautions:['Not for those with garlic allergy','May cause garlic breath','Avoid on acid-sensitive stomachs if taking more than 8 garlic cloves'],
    ageMin:3, ageMax:100,
    contraindications:['blood_thinners'],
    difficulty:'Moderate', prepTime:'30 min', effectiveness:4.5,
    tags:['cold','flu','immunity','soup','garlic'],
  },
  {
    id:'R029', name:'Oatmeal & Calendula Skin Bath',
    tagline:'Full-body skin soothing',
    description:'Colloidal oatmeal and calendula create a profoundly soothing bath that relieves widespread itching, eczema, rashes, and inflamed skin.',
    category:'skin',
    symptoms:['eczema','itching','skin_rash','dry_skin','sunburn'],
    herbs:['calendula','aloe_vera'],
    ingredients:[
      { item:'Colloidal oatmeal or rolled oats (ground to powder)', amount:'1 cup' },
      { item:'Calendula dried flowers or oil', amount:'2 tablespoons or 5 drops' },
      { item:'Aloe vera gel',                  amount:'3 tablespoons (optional)' },
      { item:'Lukewarm bath water',            amount:'Full bath' },
    ],
    steps:[
      'If using rolled oats, blend to a fine powder in a blender.',
      'Fill bath with lukewarm (not hot) water.',
      'Add oatmeal powder and whisk until water turns milky.',
      'Add calendula flowers or oil.',
      'Add aloe vera if using.',
      'Soak for 15–20 minutes.',
      'Pat skin dry gently — do not rub.',
      'Apply moisturizer immediately while skin is still slightly damp.',
    ],
    dosage:'Every other day during flare-ups',
    duration:'As needed',
    benefits:['Deeply soothes widespread itching','Reduces skin inflammation','Restores skin barrier','Safe for all ages','No harsh chemicals'],
    precautions:['Water must be lukewarm — hot water worsens eczema','Pat dry, never rub','Moisturize immediately after','Check for oat allergy first (rare)'],
    ageMin:0, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'10 min', effectiveness:4.5,
    tags:['eczema','itching','skin','bath'],
  },
  {
    id:'R030', name:'Warm Milk with Nutmeg Sleep Remedy',
    tagline:'Centuries-old sleep inducer',
    description:'A very small amount of nutmeg in warm milk contains natural sedative compounds that help induce sleep without any dependency.',
    category:'mental',
    symptoms:['insomnia','anxiety','stress'],
    herbs:['honey'],
    ingredients:[
      { item:'Warm milk', amount:'1 cup' },
      { item:'Nutmeg (freshly grated)', amount:'A tiny pinch (1/8 teaspoon max)' },
      { item:'Honey', amount:'1 teaspoon' },
    ],
    steps:[
      'Warm milk in a saucepan.',
      'Add the tiniest pinch of freshly grated nutmeg.',
      'Add honey and stir well.',
      'Drink 30–45 minutes before bedtime.',
    ],
    dosage:'1 cup nightly before bed',
    duration:'Use as needed',
    benefits:['Promotes natural drowsiness','Relaxes the mind','Warm milk provides tryptophan for serotonin','Simple and comforting','No chemical dependency'],
    precautions:['Use ONLY a tiny pinch — excessive nutmeg is toxic','Never use more than 1/8 teaspoon','Not for children under 3 without medical guidance'],
    ageMin:3, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.3,
    tags:['sleep','insomnia','bedtime','milk'],
  },
  {
    id:'R031', name:'Ginger & Peppermint Nausea Relief',
    tagline:'Fast nausea and motion sickness relief',
    description:'Ginger and peppermint are the two most studied herbs for nausea — this remedy combines them for rapid relief from morning sickness, travel sickness, or post-illness nausea.',
    category:'digestive',
    symptoms:['nausea','vomiting','dizziness','indigestion'],
    herbs:['ginger','peppermint'],
    ingredients:[
      { item:'Fresh ginger',           amount:'½ inch piece, grated' },
      { item:'Fresh peppermint leaves or dried', amount:'5 leaves or 1 tsp dried' },
      { item:'Water',                  amount:'1 cup' },
      { item:'Honey',                  amount:'1 teaspoon' },
      { item:'Lemon juice',            amount:'½ teaspoon' },
    ],
    steps:[
      'Bring water to a boil.',
      'Add ginger and peppermint.',
      'Simmer for 5 minutes.',
      'Strain into a cup.',
      'Add honey and lemon juice.',
      'Sip slowly in small amounts.',
    ],
    dosage:'Sip slowly throughout the day',
    duration:'As needed — usually helps within 15–20 minutes',
    benefits:['Reduces nausea sensation rapidly','Prevents vomiting','Calms stomach spasms','Freshens taste in mouth','Aids digestion'],
    precautions:['Sip slowly — gulping can worsen nausea','Avoid peppermint if pregnant (can relax uterus in high doses)','Keep ginger tea cool for easier sipping when nauseated'],
    ageMin:2, ageMax:100,
    contraindications:['pregnancy'],
    difficulty:'Easy', prepTime:'8 min', effectiveness:4.6,
    tags:['nausea','vomiting','digestion','motion sickness'],
  },
  {
    id:'R032', name:'Tea Tree & Neem Oil Cold Sore Treatment',
    tagline:'Antiviral cold sore remedy',
    description:'Tea tree oil\'s proven antiviral properties combined with neem\'s antimicrobial action reduce cold sores\' duration and frequency.',
    category:'skin',
    symptoms:['cold_sores','mouth_ulcers'],
    herbs:['neem'],
    ingredients:[
      { item:'Tea tree essential oil', amount:'1 drop' },
      { item:'Coconut oil (carrier)',  amount:'1 teaspoon' },
      { item:'Aloe vera gel',          amount:'½ teaspoon' },
    ],
    steps:[
      'Dilute tea tree oil in coconut oil.',
      'Mix in aloe vera gel.',
      'Using a clean cotton swab, apply directly to the cold sore.',
      'Do not touch the sore with fingers — prevents spreading.',
      'Let it absorb. Do not rinse.',
    ],
    dosage:'3–4 times daily',
    duration:'5–7 days',
    benefits:['Antiviral action shortens duration','Reduces pain and inflammation','Prevents secondary infection','Natural and gentle','Speeds healing'],
    precautions:['Never use undiluted tea tree oil on skin','Do not ingest','Keep away from inner mouth — apply on lip area only','Do not share utensils during outbreak'],
    ageMin:12, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'2 min', effectiveness:4.2,
    tags:['cold sores','herpes','lips','antiviral'],
  },
  {
    id:'R033', name:'Lavender & Brahmi Anxiety Roll-On',
    tagline:'Instant anxiety relief on the go',
    description:'A portable roll-on blend using lavender and brahmi oil that provides near-instant relief from acute anxiety, panic, and stress.',
    category:'mental',
    symptoms:['anxiety','stress','insomnia','irritability','mood_swings','palpitations'],
    herbs:['lavender','brahmi'],
    ingredients:[
      { item:'Lavender essential oil', amount:'10 drops' },
      { item:'Frankincense essential oil', amount:'5 drops (optional)' },
      { item:'Jojoba oil or sweet almond oil', amount:'10 ml (to fill roller bottle)' },
      { item:'10 ml glass roller bottle', amount:'1' },
    ],
    steps:[
      'Add lavender and frankincense drops to the roller bottle.',
      'Fill remainder with jojoba or almond oil.',
      'Cap and roll between hands to blend.',
      'Apply to pulse points: wrists, temples, and behind ears.',
      'Inhale deeply after applying to wrists.',
      'Reapply as needed.',
    ],
    dosage:'Apply to pulse points as needed',
    duration:'Use whenever anxiety strikes',
    benefits:['Near-instant calming effect','Portable and discreet','Reduces cortisol levels','Safe for regular use','Aromatic therapy proven effective'],
    precautions:['Do a patch test first','Keep away from eyes','Dilute properly — never use undiluted','Not a replacement for professional treatment in severe anxiety'],
    ageMin:8, ageMax:100,
    contraindications:[],
    difficulty:'Easy', prepTime:'5 min', effectiveness:4.5,
    tags:['anxiety','stress','aromatherapy','lavender','roll-on'],
  },
  {
    id:'R034', name:'Clove & Garlic Ear Pain Oil',
    tagline:'Soothes mild earache',
    description:'Warmed clove and garlic infused oil provides antimicrobial and analgesic relief from mild ear pain and outer ear infections.',
    category:'other',
    symptoms:['ear_pain'],
    herbs:['cloves','garlic'],
    ingredients:[
      { item:'Garlic cloves', amount:'2, crushed' },
      { item:'Clove oil or whole cloves', amount:'3 drops oil or 3 whole cloves' },
      { item:'Olive oil or coconut oil', amount:'2 tablespoons' },
    ],
    steps:[
      'Warm oil on very low heat (do not get hot — just warm).',
      'Add crushed garlic and cloves.',
      'Simmer gently for 5 minutes.',
      'Remove from heat and cool to body temperature.',
      'Strain to remove solid pieces.',
      'Using a dropper, place 2–3 drops into the affected ear.',
      'Lie on your side for 5 minutes.',
    ],
    dosage:'2–3 drops, 2–3 times daily',
    duration:'2–3 days — see doctor if not improving',
    benefits:['Antimicrobial action','Natural analgesic','Reduces inflammation','Garlic fights bacterial infection','Warming effect eases pain'],
    precautions:['ONLY for mild outer ear pain — NOT if ear drum may be perforated','Oil must be body temperature, not hot','See a doctor if severe pain, fever, or discharge'],
    ageMin:5, ageMax:100,
    contraindications:['perforated_eardrum'],
    difficulty:'Moderate', prepTime:'15 min', effectiveness:4.0,
    tags:['earache','ear pain','infection','ear'],
  },
  {
    id:'R035', name:'Triphala & Rose Water Eye Wash',
    tagline:'Natural eye care and irritation relief',
    description:'Triphala has been used in Ayurveda for millennia as an eye tonic. A diluted wash reduces redness, irritation, and strengthens vision.',
    category:'other',
    symptoms:['eye_irritation','eye_strain','dark_circles'],
    herbs:['triphala'],
    ingredients:[
      { item:'Triphala powder', amount:'½ teaspoon' },
      { item:'Clean filtered water', amount:'1 cup' },
      { item:'Rose water (pure)', amount:'1 teaspoon' },
    ],
    steps:[
      'Boil water and add triphala powder.',
      'Simmer for 5 minutes.',
      'Cool completely to room temperature.',
      'Strain multiple times through a fine cloth or coffee filter until crystal clear.',
      'Add rose water.',
      'Use an eye cup or sterile dropper to rinse eyes.',
      'Blink gently after application.',
    ],
    dosage:'Once daily at bedtime',
    duration:'2–4 weeks',
    benefits:['Reduces eye redness','Soothes eye irritation','Strengthens eye muscles','Anti-inflammatory for eyes','Traditional Ayurvedic eye care'],
    precautions:['Ensure the solution is properly strained and completely clear','Use only fresh, prepared daily','Discontinue if irritation worsens','Use filtered/boiled water only'],
    ageMin:12, ageMax:100,
    contraindications:[],
    difficulty:'Moderate', prepTime:'20 min', effectiveness:4.1,
    tags:['eyes','irritation','ayurveda','eye care'],
  },
];

// ──────────────────────────────────────────────────────────────────────────────
//  DANGER SIGNS — require doctor visit
// ──────────────────────────────────────────────────────────────────────────────
const DANGER_SIGNS = [
  { symptom:'chest_pain',       urgency:'EMERGENCY', message:'Chest pain or pressure can be a sign of a heart attack. Call emergency services or visit the emergency room immediately.', icon:'🚨' },
  { symptom:'high_fever',       urgency:'URGENT',    message:'A fever above 103°F (39.4°C) requires prompt medical attention, especially if accompanied by stiff neck, confusion, or rash.', icon:'⚠️' },
  { symptom:'shortness_breath', urgency:'EMERGENCY', message:'Difficulty breathing that is sudden or severe requires immediate emergency care.', icon:'🚨' },
  { symptom:'palpitations',     urgency:'URGENT',    message:'Persistent heart palpitations, especially with dizziness or chest pain, need medical evaluation.', icon:'⚠️' },
  { symptom:'wheezing',         urgency:'URGENT',    message:'Wheezing may indicate asthma or allergic reaction. If breathing is difficult, seek immediate care.', icon:'⚠️' },
];

// Conditions that always warrant a doctor visit when combined
const HIGH_RISK_COMBINATIONS = [
  { symptoms:['high_fever','neck_stiffness'],       message:'High fever with neck stiffness may indicate meningitis — seek emergency care immediately.' },
  { symptoms:['chest_pain','shortness_breath'],     message:'Chest pain with shortness of breath is a cardiac emergency. Call for emergency help now.' },
  { symptoms:['high_fever','skin_rash'],            message:'Fever with rash can indicate a serious infection. Seek urgent medical care.' },
  { symptoms:['severe_headache','high_fever'],      message:'Severe headache with high fever warrants immediate medical evaluation.' },
];

const PREEXISTING_CONDITIONS = [
  { id:'diabetes',                label:'Diabetes',                       icon:'💉' },
  { id:'hypertension',            label:'High Blood Pressure',            icon:'❤️' },
  { id:'heart_disease',           label:'Heart Disease',                  icon:'🫀' },
  { id:'asthma',                  label:'Asthma',                         icon:'🫁' },
  { id:'kidney_disease',          label:'Kidney Disease',                 icon:'🫘' },
  { id:'liver_disease',           label:'Liver Disease',                  icon:'🫀' },
  { id:'pregnancy',               label:'Pregnancy',                      icon:'🤰' },
  { id:'blood_thinners',          label:'On Blood Thinners (Warfarin)',   icon:'💊' },
  { id:'thyroid_disorders',       label:'Thyroid Disorder',               icon:'🦋' },
  { id:'autoimmune_disorders',    label:'Autoimmune Disorder',            icon:'🛡️' },
  { id:'hormone_sensitive_conditions', label:'Hormone-Sensitive Condition', icon:'⚗️' },
  { id:'none',                    label:'None of the above',              icon:'✅' },
];
